# ????
spring:
  mail:
    host: smtp.qq.com
    username: 1092134168@qq.com
    password: vffzjmholmbzhhje
    port: 465

--- # ?????
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_fire_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: zhaohongbo

